resource: kubernetes-1.16.7
version: 1.16.7
components:
  kubernetes: 1.16.7
  etcd: 3.3.10
  docker: docker-ce-18.09.9
images:
  - name: quay.io/external_storage/nfs-client-provisioner
    tag: v3.1.0-k8s1.11
  - name: docker.io/traefik
    tag: v1.7.11
  - name: docker.io/grafana/grafana
    tag: 6.4.3
  - name: docker.io/busybox
    tag: 1.31.0
  - name: prom/alertmanager
    tag: v0.20.0
  - name: jimmidyson/configmap-reload
    tag: v0.3.0
  - name: quay.io/coreos/kube-state-metrics
    tag: v1.9.1
  - name: prom/node-exporter
    tag: v0.18.1
  - name: prom/prometheus
    tag: v2.15.2
  - name: docker.io/coredns/coredns
    tag: 1.6.0
  - name: quay.io/coreos/flannel
    tag: v0.11.0-amd64
  - name: gcr.io/kubernetes-helm/tiller
    tag: v2.16.1
  - name: kubernetesui/dashboard
    tag: v2.0.0-beta5
  - name: kubernetesui/metrics-scraper
    tag: v1.0.1
  - name: k8s.gcr.io/metrics-server-amd64
    tag: v0.3.6
  - name: gcr.io/google-containers/pause-amd64
    tag: 3.1
  - name: docker.io/registry
    tag: 2
  - name: docker.io/alpine
    tag: 3.6
  - name: appropriate/curl
    tag: edge
  - name: docker.io/konradkleine/docker-registry-frontend
    tag: v2
  - name: weaveworks/scope
    tag: 1.12.0
  - name: calico/node
    tag: v3.7.3
  - name: calico/cni
    tag: v3.7.3
  - name: calico/kube-controllers
    tag: v3.7.3
  - name: grafana/loki
    tag: v1.2.0
  - name: grafana/promtail
    tag: v1.2.0
  - name: rook/ceph
    tag: v1.1.6
  - name: quay.io/cephcsi/cephcsi
    tag: v1.2.1
  - name: quay.io/k8scsi/csi-node-driver-registrar
    tag: v1.1.0
  - name: quay.io/k8scsi/csi-provisioner
    tag: v1.3.0
  - name: quay.io/k8scsi/csi-snapshotter
    tag: v1.2.0
  - name: quay.io/k8scsi/csi-attacher
    tag: v1.2.0
  - name: ceph/ceph
    tag: v14.2.4-20190917
  - name: k8s.gcr.io/node-problem-detector
    tag: v0.8.0
  - name: chartmuseum/chartmuseum
    tag: v0.10.0
  - name: docker.io/bitnami/nginx
    tag: 1.16.1-debian-9-r52
  - name: docker.io/bitnami/kubeapps-apprepository-controller
    tag: 1.7.1-scratch-r0
  - name: docker.io/bitnami/kubeapps-chart-repo
    tag: 1.9.0-r2
  - name: docker.io/bitnami/kubectl
    tag: 1.16.3-r17
  - name: docker.io/bitnami/kubeapps-tiller-proxy
    tag: 1.7.1-scratch-r0
  - name: docker.io/bitnami/kubeapps-chartsvc
    tag: 1.9.0-r0
  - name: docker.io/kubeoperator/kubeapps-plus
    tag: v1.0
  - name: docker.io/bitnami/mongodb
    tag: 4.0.13-debian-9-r22
  - name: docker.io/bitnami/minideb
    tag: stretch
  - name: docker.io/bitnami/oauth2-proxy
    tag: 4.0.0-r92
  - name: nvidia/k8s-device-plugin
    tag: 1.0.0-beta

vars:
  bin_dir: "/usr/local/bin"
  ca_dir: "/etc/kubernetes/ssl"
  CONTAINER_RUNTIME: "docker"
  base_dir: "/opt/kubeOperator-kube-bin/1.16.7"
  kube_version: "1.16.7"
  docker_version: "18.09.9"
  etcd_version: "3.3.10"
  helm_version: "2.16.1"
  repo_port: 8089
  registry_port: 8099
  registry_prefix: "registry.kubeops.io"
  download_path: "repository/raw/1.16.7/k8s.1-16-7.tar.gz"
  file_name: "k8s.1-16-7.tar.gz"

  #kubelet
  SANDBOX_IMAGE_NAME: "gcr.io/google-containers/pause-amd64"
  SANDBOX_VERSION: "3.1"
  
  #dns
  dns_install: true
  dns_image: "docker.io/coredns/coredns"
  dns_version: "1.6.0"

  #dashboard
  dashboard_install: true
  dashboard_image: "kubernetesui/dashboard"
  dashboard_version: "v2.0.0-beta5"
  metrics_scraper_image: kubernetesui/metrics-scraper
  metrics_scraper_version: v1.0.1

  #metrics_server
  metrics_server_amd64_image: k8s.gcr.io/metrics-server-amd64
  metrics_server_amd64_version: v0.3.6
  metrics_server_install: true


  #traefik
  traefik_version: "v1.7.11"
  traefik_image: "docker.io/traefik"
  
  #helm
  helm_namespace: kube-system
  helm_cert_cn: helm001
  tiller_sa: tiller
  tiller_cert_cn: tiller001
  tiller_image: "gcr.io/kubernetes-helm/tiller"
  tiller_version: "v2.16.1"

  #flannel
  NODE_WITH_MULTIPLE_NETWORKS: "true"
  flanneld_image: "quay.io/coreos/flannel"
  flanneld_version: "v0.11.0-amd64"

  #calico
  calico_ver: "v3.7.3"

  #registry
  REGISTRY_ACCOUNT_NAME: admin
  REGISTRY_ACCOUNT_PASSWORD: admin123
  IMAGE_PULL_SECRET: registry-fit2cloud-com-key

  #prometheus
  alertmanager_image:  prom/alertmanager
  alertmanager_version: v0.20.0
  node_exporter_image: prom/node-exporter
  node_exporter_version: v0.18.1
  prometheus_image: prom/prometheus
  prometheus_version: v2.15.2
  kube_state_metrics_image: quay.io/coreos/kube-state-metrics
  kube_state_metrics_version: v1.9.1
  configmap_reload_image: jimmidyson/configmap-reload
  configmap_reload_version: v0.3.0
  busybox_image: docker.io/busybox
  busybox_version: 1.31.0

  #grafana
  grafana_image: docker.io/grafana/grafana
  grafana_version: 6.4.3
  curl_image: appropriate/curl
  curl_version: edge

  #scope
  scope_image: weaveworks/scope
  scope_version: 1.12.0

  #loki
  loki_image: grafana/loki
  loki_version: v1.2.0
  promtail_image: grafana/promtail
  promtail_version: v1.2.0
  loki_install: true


  #rook
  storage_rook_ceph_install: true
  rook_ceph_image: rook/ceph
  rook_ceph_version: v1.1.6
  cephcsi_image: quay.io/cephcsi/cephcsi
  cephcsi_version: v1.2.1
  csi_node_driver_registrar_image: quay.io/k8scsi/csi-node-driver-registrar
  csi_node_driver_registrar_version: v1.1.0
  csi_provisioner_image: quay.io/k8scsi/csi-provisioner
  csi_provisioner_version: v1.3.0
  csi_snapshotter_image: quay.io/k8scsi/csi-snapshotter
  csi_snapshotter_version: v1.2.0
  csi_attacher_image: quay.io/k8scsi/csi-attacher
  csi_attacher_version: v1.2.0
  ceph_ceph_image: ceph/ceph
  ceph_ceph_version: v14.2.4-20190917

  #eventer
  node_problem_detector_image: k8s.gcr.io/node-problem-detector
  node_problem_detector_version: v0.8.0
  npd_install: true

  #kubeapps
  kubeapps_install: true
  kubeapps_registry_hostname: registry.kubeapps.fit2cloud.com
  kubeapps_chartmuseum_hostname: chartmuseum.kubeapps.fit2cloud.com
  chartmuseum_image: chartmuseum/chartmuseum
  chartmuseum_version: v0.10.0
  kubeapps_nginx_image: docker.io/bitnami/nginx
  kubeapps_nginx_version: 1.16.1-debian-9-r52
  kubeapps_apprepository_controller_image: docker.io/bitnami/kubeapps-apprepository-controller
  kubeapps_apprepository_controller_version: 1.7.1-scratch-r0
  kubeapps_chart_repo_image: docker.io/bitnami/kubeapps-chart-repo
  kubeapps_chart_repo_version: 1.9.0-r2
  kubeapps_kubectl_image: docker.io/bitnami/kubectl
  kubeapps_kubectl_version: 1.16.3-r17
  kubeapps_tiller_proxy_image: docker.io/bitnami/kubeapps-tiller-proxy
  kubeapps_tiller_proxy_version: 1.7.1-scratch-r0
  kubeapps_chartsvc_image: docker.io/bitnami/kubeapps-chartsvc
  kubeapps_chartsvc_version: 1.9.0-r0
  kubeappsplus_dashboard_image: docker.io/kubeoperator/kubeapps-plus
  kubeappsplus_dashboard_version: v1.0
  kubeapps_mongodb_image: docker.io/bitnami/mongodb
  kubeapps_mongodb_version: 4.0.13-debian-9-r22
  kubeapps_minideb_image: docker.io/bitnami/minideb
  kubeapps_minideb_version: stretch
  kubeapps_oauth2_proxy_image: docker.io/bitnami/oauth2-proxy
  kubeapps_oauth2_proxy_version: 4.0.0-r92
  
  #gpu
  gpu_install: false
